package com.projetPfe.entities;

public enum DossierDelegueType {
    SCOLARITE,
    SOIN_MEDICAL,
    INVESTISSEMENT,
    ECONOMIE_SUR_SALAIRE,
    CONTRAT_COMMERCIALE,
    FORMATION_PROFESSIONEL,
    EMPREINT_EXTERIEUR
}
