CREATE TABLE IF NOT EXISTS `transfert` (
  `refTransfert` VARCHAR(45) PRIMARY KEY NOT NULL,
  `typeTransfert` ENUM('FINANCIER','COMMERCIALE') NOT NULL,
  `montantTransfert` DOUBLE NOT NULL,
  `deviseTransfert` VARCHAR(3) NOT NULL,
  `datecre` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `etat` ENUM('TRAITEMENT','BROUILLON','ANNULE','VALIDE','CLOTURE','ENVOYE','SUSPENDU') NOT NULL,
  `dateEcheance` TIMESTAMP NULL DEFAULT NULL,
  `natureTransfert` ENUM('COURANT','PERMANENT') NOT NULL,
  `frais` DOUBLE NULL DEFAULT NULL
);


